import { LandmarksPolicy, LandmarksPolicyData, Policy } from "./landmarks-policy.js"

function html5_() : LandmarksPolicy {
    return new Policy({
        VoidElements: ["area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "meta", "param", "source", "track", "wbr"],
        ContentElements: [
            "html",
            "head",
            "title",
            //"base",
            //"link",
            //"meta",
            "style",
            "body",
            "article",
            "section",
            "nav",
            "aside",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "header",
            "footer",
            "address",
            "p",
            //"hr",
            "pre",
            "blockquote",
            "ol",
            "ul",
            "li",
            "dl",
            "dt",
            "dd",
            "figure",
            "figcaption",
            "main",
            "div",
            "a",
            "em",
            "strong",
            "small",
            "s",
            "cite",
            "q",
            "dfn",
            "abbr",
            "ruby",
            "rb",
            "rt",
            "rtc",
            "rp",
            "data",
            "time",
            "code",
            "var",
            "samp",
            "kbd",
            "sub",
            "sup",
            "i",
            "b",
            "u",
            "mark",
            "bdi",
            "bdo",
            "span",
            //"br",
            //"wbr",
            "ins",
            "del",
            "picture",
            //"img",
            "iframe",
            //"embed",
            "object",
            //"param",
            "video",
            "audio",
            //"source",
            //"track",
            "map",
            //"area",
            "table",
            "caption",
            "colgroup",
            //"col",
            "tbody",
            "thead",
            "tfoot",
            "tr",
            "td",
            "th",
            "form",
            "label",
            //"input",
            "button",
            "select",
            "datalist",
            "optgroup",
            "option",
            "textarea",
            //"keygen",
            "output",
            "progress",
            "meter",
            "fieldset",
            "legend",
            "details",
            "summary",
            "menu",
            "menuitem",
            "dialog",
            "script",
            "noscript",
            "template",
            "canvas",
        ],
        OpaqueElements: ["script", "style", "textarea", "title"],
        AutoclosingEndTags: ["svg", "math", "pre", "p"],
        AutocloseByParent: ["head", "body", "li", "dt", "dd", "p", "rb", "rt", "rtc", "rp", "optgroup", "option", "thead", "tbody", "tfoot", "tr", "td", "th"],
        AutocloseBySibling: [
            ["a", ["a"]],
            ["li", ["li"]],
            ["dt", ["dt", "dd"]],
            ["rb", ["rb", "rt", "rtc", "rp"]],
            ["rt", ["rb", "rt", "rtc", "rp"]],
            ["rtc", ["rb", "rt", "rtc", "rp"]],
            ["rp", ["rb", "rt", "rtc", "rp"]],
            ["optgroup", ["optgroup"]],
            ["thead", ["tbody", "tfoot"]],
            ["tbody", ["tbody", "tfoot"]],
            ["tfoot", ["tbody"]],
            ["tr", ["tr"]],
            ["td", ["td", "th"]],
            ["th", ["td", "th"]],
            ["head", ["body"]],
            ["option", ["option", "optgroup"]],
            ["p", [
                "address", "article", "aside", "blockquote", "div", "dl", "fieldset", "footer", "form",
                "h1", "h2", "h3", "h4", "h5", "h6", "header", "hgroup", "hr", "main", "nav",
                "ol", "p", "pre", "section", "table", "ul"
            ]],
            ["h1", ["h1", "h2", "h3", "h4", "h5", "h6"]],
            ["h2", ["h1", "h2", "h3", "h4", "h5", "h6"]],
            ["h3", ["h1", "h2", "h3", "h4", "h5", "h6"]],
            ["h4", ["h1", "h2", "h3", "h4", "h5", "h6"]],
            ["h5", ["h1", "h2", "h3", "h4", "h5", "h6"]],
            ["h6", ["h1", "h2", "h3", "h4", "h5", "h6"]],
        ],
        WildcardEndTags: [],
    });
}

export const html5 = html5_();